# Generated by Django 5.0 on 2023-12-21 14:21

from django.db import migrations, models

# this file was created by the command :  python .\manage.py makemigrations
# we use the above command to migrate changes (or to create new models) that we have made to our db model in django to our db schema in mysql.
# to add it to the db you need to run: py manage.py migrate
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
