# Generated by Django 5.0 on 2023-12-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(default='-', max_length=30, verbose_name='Brand'),
        ),
    ]
