# Generated by Django 5.0 on 2023-12-29 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_item_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='brand',
        ),
    ]
