# Generated by Django 5.0 on 2023-12-29 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_item_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
